# Workflow parameters

# number of simulations to run
K: 5000

# Proportion of data to use for training
train: 0.8

# Proportion of data to use for testing
test: 0.1

# Proporition of data to use for validation
val: 0.1

# Path to gene models used for simulations
gff: "../config/Osativa_323_v7.0.gene.gff3"

# Dimmension of images will be nidv*nloc*3
# Number of individual genomes to sample
nidv: 128

# Number of loci to sample
nloc: 128

# Measurement of genetic distance between loci
distMethod: "manhattan"

# method for clustering genomes based on genetic distance
clustMethod: "complete"